config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  get "/inicio", to: "welcome#index"
  resources :coins
  root to: "welcome#index"

  resources :arrecadacao

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arrecadacao_controller.rb
class ArrecadacaoController < ApplicationController

  def index
    @arrecadacao = JSON.parse(File.read("app/assets/documents/consolidadinho.json"))
  end

end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]

  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    if @coin.url_image == nil || @coin.url_image == ''
      @coin.url_image = "http://site.moeda.digital/wp-content/uploads/2016/12/opengraph_fb_moeda_site.jpg"
    end

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: "A moeda #{@coin.description} foi criada com sucesso!" }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: "A moeda #{@coin.description} foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: "A moeda #{@coin.description} foi removida com sucesso!" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_coin
    @coin = Coin.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def coin_params
    params.require(:coin).permit(:description, :acronym, :url_image)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  require "rubygems"
  require "json"

  @jsonObject = ''
  @meu_nome = ''
  @meu_curso = ''


  def index
    @jsonObject = JSON.parse(File.read("app/assets/documents/consolidadinho.json"))
    @meu_curso = params[:curso]
    @meu_nome = params[:nome]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def dataBR(data_us)
		data_us.strftime("%d/%m/%Y")
	end

	def appName
		"Crypto Wallet App"
	end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/arrecadacao/_tabelaJson.html.erb
<hr>
<h3>Leitura de um arquivo JSON</h3>
<table class="table">
    <tr>
        <td>#</td>
        <td>MES</td>
        <td>UC</td>
        <td>NOME</td>
        <td>CONSUMO</td>
    </tr>
    <% @arrecadacao.each_with_index do |orgao, index| %>
        <tr>
            <td><%= index + 1 %></td>
            <td><%= orgao["MES"] %></td>
            <td><%= orgao["UC"] %></td>
            <td><%= orgao["NOME"] %></td>
            <td><%= orgao["FAT_CONSUMO"] %></td>
        </tr>
    <% end %>
</table>

app/views/arrecadacao/index.html.erb
<div ng-controller="PainelArrecadaController">
	<code>{{json}}</code>
</div>

<hr>

<%= @arrecadacao %>

<%= render "tabelaJson" %>

<!--Angular -->
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.2/angular.min.js"></script>
<script src="https://code.angularjs.org/1.6.2/angular-animate.js"></script>

<!--Modulo Angular -->
<script src="/angular/angular-locale_pt-br.js"></script>
<script src="/angular/app.module.js"></script>
<script src="/angular/controllers/PainelArrecadaController.js"></script>

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="field">
    <%= form.label :url_image %>
    <%= form.text_field :url_image %>
    <% unless coin.url_image == nil%>
      <%= image_tag coin.url_image, width:25, height: 25 %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Alterar Moeda</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Mostrar', @coin %> |
<%= link_to 'Voltar', coins_path %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moedas</h1>

<table>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Sigla</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, width:25, height: 25 %></td>
        <td><%= link_to 'Mostrar', coin %></td>
        <td><%= link_to 'Editar', edit_coin_path(coin) %></td>
        <td><%= link_to 'Apagar', coin, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Moeda', new_coin_path %>

app/views/coins/new.html.erb
<h1>New Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Back', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrição:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Logo:</strong>
  <%= image_tag @coin.url_image, width:25, height: 25 %>
</p>

<%= link_to 'Editar', edit_coin_path(@coin) %> |
<%= link_to 'Voltar', coins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br" ng-app="app">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="msapplication-tap-highlight" content="no">


  <title>CryptoWallet</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/welcome/_menu.html.erb
<ul>
    <li>
        <%= link_to  "Cadastro de moedas", coins_path %>
    </li>
</ul>

app/views/welcome/index.html.erb
<h1><%= appName %></h1>

<h3>Seja bem-vindo</h3>

<h5>Data: <%= dataBR(Date.today) %></h5>

<%= render "menu" %>

<p>Meu nome é: <strong><%= @meu_nome %></strong></p>
<p>Meu curso é: <strong><%= @meu_curso %></strong></p>